### ISSUE TITLE
"/config" for actions expects "args" to be an array, but the schema states it is a string

### ISSUE THREAD

**Issue by pszynk** [guard-project/lcp#3]
The problem is the line here:

https://github.com/guard-project/lcp/blob/e44d06ed37f37813ffc7e0bc9e9226e6c0f13d3a/resource/config.py#L76

while the schema states:

https://github.com/guard-project/lcp/blob/e44d06ed37f37813ffc7e0bc9e9226e6c0f13d3a/swagger/schema.yaml#L37-L42

if `args` is a string then `[cmd] + data.get('args', [])` for non-empty `args` returns an error (concatenating list and string).

For me `args` as an array look better, at least at the first glance.

**Comment by alexcarrega** [comment]
I think is a problem of swagger.

If you see the `Config_Action_Request_Schema`, the `args` field is set as `string` but with `many=True`.
https://github.com/guard-project/lcp/blob/71cbb7d03cbee03544b7f131d0f7c9cfd45f4d69/schema/config.py#L19-L28

**Comment by alexcarrega** [comment]
Fixed
