### ISSUE TITLE
double 'error' field in response

### ISSUE THREAD

**Issue by pszynk** [guard-project/lcp#5]
Problem in lines:

https://github.com/guard-project/lcp/blob/e44d06ed37f37813ffc7e0bc9e9226e6c0f13d3a/resource/config.py#L79-L80

https://github.com/guard-project/lcp/blob/e44d06ed37f37813ffc7e0bc9e9226e6c0f13d3a/lib/response.py#L25-L35

and

https://github.com/guard-project/lcp/blob/e44d06ed37f37813ffc7e0bc9e9226e6c0f13d3a/utils/sequence.py#L15-L16

For the `Content_Response(output).add(resp)` `output` already contains a field `error`. But `Base_Response` in `__init__` also has an optional argument `error`. When the `__data` method is executed we get an error:

```
type object got multiple values for keyword argument 'error'
```

because `error` is passed in `self.data` and `error=self.error`

**Comment by alexcarrega** [comment]
Fixed
