### ISSUE TITLE
Modifying parameters not present in config file (yaml, json, maybe more)

### ISSUE THREAD

**Issue by pszynk** [guard-project/lcp#8]
let's assume that agent has parameters like:

```
param_a
param_b
```

if the configuration looks like

```json
//config.json
{  
 "param_a": 777
}
```

and we want to modify `param_b` which is not present in this  `config.json` (or `.yaml`) by calling CB API:

```
PUT http://server/instance/agent/myagent@myexecenv

{
  "id": "myagent@myexecenv",
  "operations": [
    {
      "parameters": [
        {
          "id": "param_b",
          "value": 2
        }
      ]
    }
  ]
}
```
this line:
https://github.com/guard-project/lcp/blob/71fd9b9d785cc1ca4d7cae8dcfc5f7349e978c30/lib/parser.py#L65
will throw an `KeyError` which is not caught. If parameter is not found in path than it should be added to the path.

**Comment by pszynk** [comment]
Also, something came to my mind. If a configuration is nested, like so:

```json
{
  "param_a":  { 
    "param_b": {
      "param_c": 1
    }
  }
}
```

then in the absence of `param_a` when setting `param_c` you'll have to construct the whole path: `param_a.param_b.param_c`

**Comment by alexcarrega** [comment]
First point: the id of the agent in the endpoint is non necessary is it is already present in the request body or viceversa.

Second point: before to set the value, you have to define this parameter in the agent catalog. It is not necessary that this parameter is already present in the related configuration files, CB-Manager adds it if not present.

Simple example:

```json
{
    "id": "param-b",
    "type": "integer",
    "example": 777,
    "description": "...",
    "config": {
        "schema": "yaml",
        "source": "<absolute path of the config.json>",
        "path": [
            "param-b"
        ]
    }
}
```

**Comment by pszynk** [comment]
yeah, I wrote this elaborate example, but didn't send you the Exception, stupid me.
I assume this parameter is declared in catalog.

This is an Exception:
<details>
<summary>Exception while serving /config</summary>
<p>




```
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]: Traceback (most recent call last):
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/guard/git/lcp/resource/config.py", line 89, in __parameters
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     output.update(self.parsers.get(schema)(schema, source, path, value))
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/guard/git/lcp/lib/parser.py", line 65, in yaml_parser
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     old_value = d[path[-1]]
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]: KeyError: 'poll_interval'
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]: During handling of the above exception, another exception occurred:
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]: Traceback (most recent call last):
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/lib/python3.9/site-packages/waitress/channel.py", line 349, in service
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     task.service()
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/lib/python3.9/site-packages/waitress/task.py", line 169, in service
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     self.execute()
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/lib/python3.9/site-packages/waitress/task.py", line 439, in execute
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     app_iter = self.channel.server.application(environ, start_response)
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/lib/python3.9/site-packages/falcon/api.py", line 269, in __call__
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     responder(req, resp, **params)
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/guard/git/lcp/resource/config.py", line 41, in on_post
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     output = self.__parameters(data)
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/guard/git/lcp/resource/config.py", line 98, in __parameters
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     return Bad_Request_Response(e, message=msg, type='parameter', data=data)
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:   File "/opt/guard-lcp/guard/git/lcp/lib/response.py", line 73, in __init__
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]:     super().__init__(exception.title if exception is not None else 'Request not valid',
Jun 29 14:51:24 guard-uc2-router guard-lcp.sh[777]: AttributeError: 'KeyError' object has no attribute 'title'
```

</p>
</details>  


Here `poll_interval` plays the role of `param_b` from the example. 
This error won't appear for current configuration file:

```yaml
rules:
  - 'rule1'
  - 'rule2'
poll_interval: 3
```

but will apperar when the configuration file is exackly


```yaml
rules:
  - 'rule1'
  - 'rule2'

# notice the lack of `poll_interva` entry!
```

**Comment by alexcarrega** [comment]
I have to check if the insertion of new parameters in the config file works.

**Comment by alexcarrega** [comment]
I fixed the error, but I think it should better to update the version after the review.
@pszynk  Do you need this feature available for the review?

**Comment by pszynk** [comment]
> @pszynk Do you need this feature available for the review?
@alexcarrega No I can work around that by preparing a starting config file with all parameters declared. 

Either way, when modifying two parameters `rules` and `poll_interval`, the file was partially updated, new `rules` appeared. Because the `rules` field was present in original config file before modification. The `poll_interval` parameter was ignored and CB return error code 4xx (426 or 422) i think.

**So this is not crucial for the presentation**, at least from my point. If anybody would encounter this error they also can bypass it by preparing a full config file with all params declared.

**Comment by alexcarrega** [comment]
Ok, I will update LCP after the review.

For the review, please check that the parameters are present in the configuration files.

**Comment by alexcarrega** [comment]
Hi, I made some local changes to LCP (but without a push).
Now it can add new parameter in the file even if this one is total empty.
The only open problem regards the management of array. If you want to update an array in a specific position it is necessary to define the path in the agent catalog as list of hybrid string / int elements that is not allowed at this moment. I will work about this specifically to avoid some problem with Elasticsearch and its mapping definition.

**Comment by pszynk** [comment]
Nice. 

As for updating an array at specific index. For myself I don't think I'b be using such functionality.
I can see that the implementation would be problematic, many more edge scenarios.

Also binding a parameter to specific index in the array seems like a bad design for configuration.
The requirement for an array or rather a list in case of yaml/json to keep its order is asking for trouble.

I would suggest not supporting such an operation for API and require the update of the whole list value.
It is more verbose, true, but it could be made more manageable by using GUI.
E.g. GUI loads whole list, allows to modify selected indexes, but sends the request with a whole list.

**Comment by alexcarrega** [comment]
Ok, so I assume only a path of key strings.

**Comment by alexcarrega** [comment]
I uploaded a new version of LCP with the accorded changes.
